apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuci-role-binding
subjects:
- kind: ServiceAccount
  name: kuci
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuci
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kuci
    spec:
      serviceAccountName: kuci
      containers:
      - name: kuci
        image: zihao/play-kuci:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
    volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
